// Code generated by crec-gen (scaffold). Customize as needed.

package dvp

import (
	"context"
	"encoding/json"
	"fmt"

	workflows "github.com/smartcontractkit/crec-workflow-utils"
	apiClient "github.com/smartcontractkit/crec-api-go/client"
	"github.com/smartcontractkit/crec-sdk-ext-dvp/events"
)

// DecodedEvent wraps WatcherEventPayload with a decoded ConcreteEvent.
//
// Add domain-specific enrichment fields here. For example:
//
//	FundTokenData      *events.FundTokenData
//	DistributorRequest *events.DistributorRequest
//	PaymentRequests    []workflows.PaymentRequest
type DecodedEvent struct {
	apiClient.WatcherEventPayload
	// ConcreteEvent is the decoded event struct matching the blockchain event type.
	ConcreteEvent events.ConcreteEvent
	// TODO: Add enrichment fields from your handler's reference data.
}

// EventName returns the parsed event name from the payload.
func (e DecodedEvent) EventName() events.EventName {
	verifiableEvent, err := workflows.DecodeVerifiableEvent(e.WatcherEventPayload.VerifiableEvent)
	if err != nil || verifiableEvent == nil {
		return events.EventUnknown
	}
	name, ok := events.ParseEventName(verifiableEvent.Name)
	if !ok {
		return events.EventUnknown
	}
	return name
}

// DecodeFromEvent extracts the WatcherEventPayload from an apiClient.Event
// and decodes the ConcreteEvent based on the event type.
//
// Extend this function to decode enrichment data from reference data.
// See the handler for which enrichment fields are populated.
func DecodeFromEvent(_ context.Context, event apiClient.Event) (DecodedEvent, error) {
	payload, err := event.Payload.AsWatcherEventPayload()
	if err != nil {
		return DecodedEvent{}, fmt.Errorf("extract watcher payload: %w", err)
	}

	verifiableEvent, err := workflows.DecodeVerifiableEvent(payload.VerifiableEvent)
	if err != nil {
		return DecodedEvent{}, fmt.Errorf("decode verifiable event: %w", err)
	}
	if verifiableEvent == nil {
		return DecodedEvent{}, fmt.Errorf("verifiable event is nil")
	}

	name, ok := events.ParseEventName(verifiableEvent.Name)
	if !ok {
		return DecodedEvent{}, fmt.Errorf("unsupported event name: %s", verifiableEvent.Name)
	}
	decoders := events.EventDecoders()
	decoder, ok := decoders[name]
	if !ok {
		return DecodedEvent{}, fmt.Errorf("no decoder for event: %s", name)
	}

	evmEvent, err := verifiableEvent.ChainEvent.AsEVMEvent()
	if err != nil {
		return DecodedEvent{}, fmt.Errorf("convert to evm event: %w", err)
	}

	params := make(map[string]string, len(*evmEvent.Params))
	for k, v := range *evmEvent.Params {
		params[k] = fmt.Sprintf("%v", v)
	}

	concrete, err := decoder(params, evmEvent.TxHash)
	if err != nil {
		return DecodedEvent{}, fmt.Errorf("decode %s: %w", name, err)
	}

	// TODO: Decode enrichment data from reference data.
	//
	// referenceData, err := workflows.GetReferenceDataFromVerifiableEvent(*verifiableEvent)
	// if err != nil {
	//     return DecodedEvent{}, fmt.Errorf("decode reference data: %w", err)
	// }
	// if referenceData != nil {
	//     // Decode on-chain reference data into your custom types.
	//     // Add private decode helpers below this function.
	// }

	return DecodedEvent{
		WatcherEventPayload: payload,
		ConcreteEvent:       concrete,
	}, nil
}

// Unused import guard.
var _ = json.Marshal
