# CRE Workflow Settings File

local-simulation:
  user-workflow:
      workflow-name: "watcher-dvp"
  workflow-artifacts:
    workflow-path: "./bundle/binary.wasm"
    config-path: "./config.yaml"

staging:
  user-workflow:
    workflow-name: "watcher-dvp"
  workflow-artifacts:
    workflow-path: "./bundle/binary.wasm"
    config-path: "./config.yaml"
