// Code generated by crec-gen. DO NOT EDIT.

package bundle

import "encoding/json"

// ParamsSchemas maps event names to their auto-generated JSON Schema
// derived from the Solidity ABI event parameters.
var ParamsSchemas = map[string]json.RawMessage{
	"SettlementOpened": json.RawMessage(`
		{
			"type": "object",
			"properties": {
				"settlement_id": {
					"type": "string",
					"description": "uint256"
				},
				"settlement_hash": {
					"type": "string",
					"description": "bytes32 hex"
				}
			},
			"required": [
				"settlement_id",
				"settlement_hash"
			]
		}
	`),
	"SettlementAccepted": json.RawMessage(`
		{
			"type": "object",
			"properties": {
				"settlement_id": {
					"type": "string",
					"description": "uint256"
				},
				"settlement_hash": {
					"type": "string",
					"description": "bytes32 hex"
				}
			},
			"required": [
				"settlement_id",
				"settlement_hash"
			]
		}
	`),
	"SettlementClosing": json.RawMessage(`
		{
			"type": "object",
			"properties": {
				"settlement_id": {
					"type": "string",
					"description": "uint256"
				},
				"settlement_hash": {
					"type": "string",
					"description": "bytes32 hex"
				}
			},
			"required": [
				"settlement_id",
				"settlement_hash"
			]
		}
	`),
	"SettlementSettled": json.RawMessage(`
		{
			"type": "object",
			"properties": {
				"settlement_id": {
					"type": "string",
					"description": "uint256"
				},
				"settlement_hash": {
					"type": "string",
					"description": "bytes32 hex"
				}
			},
			"required": [
				"settlement_id",
				"settlement_hash"
			]
		}
	`),
	"SettlementCanceling": json.RawMessage(`
		{
			"type": "object",
			"properties": {
				"settlement_id": {
					"type": "string",
					"description": "uint256"
				},
				"settlement_hash": {
					"type": "string",
					"description": "bytes32 hex"
				}
			},
			"required": [
				"settlement_id",
				"settlement_hash"
			]
		}
	`),
	"SettlementCanceled": json.RawMessage(`
		{
			"type": "object",
			"properties": {
				"settlement_id": {
					"type": "string",
					"description": "uint256"
				},
				"settlement_hash": {
					"type": "string",
					"description": "bytes32 hex"
				}
			},
			"required": [
				"settlement_id",
				"settlement_hash"
			]
		}
	`),
}
