// Code generated by crec-gen. DO NOT EDIT.

package operations

import (
	_ "embed"
	"fmt"
	"strings"

	"github.com/ethereum/go-ethereum/accounts/abi"
)

//go:embed CCIPDVPCoordinatorU.abi.json
var ccipdvpCoordinatorUABIJSON string

var (
	ccipdvpCoordinatorUABI *abi.ABI
)

func init() {
	var err error

	ccipdvpCoordinatorUABI, err = parseABI(ccipdvpCoordinatorUABIJSON)
	if err != nil {
		panic(fmt.Sprintf("failed to parse CCIPDVPCoordinatorU ABI: %v", err))
	}

}

func parseABI(jsonABI string) (*abi.ABI, error) {
	parsed, err := abi.JSON(strings.NewReader(jsonABI))
	if err != nil {
		return nil, err
	}
	return &parsed, nil
}

// CCIPDVPCoordinatorUABI returns the parsed CCIPDVPCoordinatorU ABI.
func CCIPDVPCoordinatorUABI() *abi.ABI {
	return ccipdvpCoordinatorUABI
}
