// Code generated by crec-gen. DO NOT EDIT.

package operations

import (
	_ "embed"
	"fmt"
	"strings"

	"github.com/ethereum/go-ethereum/accounts/abi"
)

//go:embed CCIPDVPCoordinator.abi.json
var ccipdvpCoordinatorABIJSON string

var (
	ccipdvpCoordinatorABI *abi.ABI
)

func init() {
	var err error

	ccipdvpCoordinatorABI, err = parseABI(ccipdvpCoordinatorABIJSON)
	if err != nil {
		panic(fmt.Sprintf("failed to parse CCIPDVPCoordinator ABI: %v", err))
	}

}

func parseABI(jsonABI string) (*abi.ABI, error) {
	parsed, err := abi.JSON(strings.NewReader(jsonABI))
	if err != nil {
		return nil, err
	}
	return &parsed, nil
}

// CCIPDVPCoordinatorABI returns the parsed CCIPDVPCoordinator ABI.
func CCIPDVPCoordinatorABI() *abi.ABI {
	return ccipdvpCoordinatorABI
}
