// Code generated by crec-gen. DO NOT EDIT.

package operations

import (
	"fmt"
	"log/slog"

	"github.com/ethereum/go-ethereum/common"
)

// Options defines the configuration for creating a new extension.
type Options struct {
	Logger         *slog.Logger
	AccountAddress string

	CCIPDVPCoordinatorUAddress string
}

func (o *Options) validate() error {
	if !common.IsHexAddress(o.AccountAddress) {
		return fmt.Errorf("invalid AccountAddress: %q", o.AccountAddress)
	}

	if !common.IsHexAddress(o.CCIPDVPCoordinatorUAddress) {
		return fmt.Errorf("invalid CCIPDVPCoordinatorUAddress: %q", o.CCIPDVPCoordinatorUAddress)
	}

	return nil
}

// Extension provides methods for preparing operations.
type Extension struct {
	logger                     *slog.Logger
	accountAddress             common.Address
	ccipdvpCoordinatorUAddress common.Address
}

// New creates a new extension with the provided options.
func New(opts *Options) (*Extension, error) {
	if opts == nil {
		return nil, fmt.Errorf("options is required")
	}

	if err := opts.validate(); err != nil {
		return nil, fmt.Errorf("invalid options: %w", err)
	}

	logger := opts.Logger
	if logger == nil {
		logger = slog.Default()
	}

	logger.Info("creating CREC SDK extension")

	return &Extension{
		logger:                     logger,
		accountAddress:             common.HexToAddress(opts.AccountAddress),
		ccipdvpCoordinatorUAddress: common.HexToAddress(opts.CCIPDVPCoordinatorUAddress),
	}, nil
}
