// Code generated by crec-gen. DO NOT EDIT.

package operations

import (
	"crypto/rand"
	"fmt"
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/common"

	transactTypes "github.com/smartcontractkit/crec-sdk/transact/types"
)

var (
	_ = rand.Read
	_ = fmt.Sprintf
	_ = big.NewInt
	_ *abi.ABI
	_ = common.Address{}
	_ *transactTypes.Operation
)

// PrepareCCIPDVPCoordinatorOperation prepares a generic operation on CCIPDVPCoordinator.
// Use this for methods not covered by the type-safe Prepare* functions.
func (e *Extension) PrepareCCIPDVPCoordinatorOperation(method string, args ...interface{}) (*transactTypes.Operation, error) {
	return e.prepareOperation(CCIPDVPCoordinatorABI(), e.ccipdvpCoordinatorAddress, method, args...)
}

func (e *Extension) prepareCCIPDVPCoordinatorOp(method string, args ...interface{}) (*transactTypes.Operation, error) {
	return e.prepareOperation(CCIPDVPCoordinatorABI(), e.ccipdvpCoordinatorAddress, method, args...)
}

func cloneBigInt(v *big.Int) *big.Int {
	if v == nil {
		return big.NewInt(0)
	}

	return new(big.Int).Set(v)
}

func (e *Extension) operationDeadline() *big.Int {
	return cloneBigInt(e.defaultDeadline)
}

func (e *Extension) newOperationWithTransactions(
	txs ...transactTypes.Transaction,
) (*transactTypes.Operation, error) {
	opID, err := generateOperationID()
	if err != nil {
		return nil, fmt.Errorf("generate operation ID: %w", err)
	}

	copiedTxs := make([]transactTypes.Transaction, len(txs))
	copy(copiedTxs, txs)

	return &transactTypes.Operation{ID: opID, Deadline: e.operationDeadline(), Account: e.accountAddress, Transactions: copiedTxs}, nil
}

func (e *Extension) prepareOperation(
	contractABI *abi.ABI,
	target common.Address,
	method string,
	args ...interface{},
) (*transactTypes.Operation, error) {
	calldata, err := contractABI.Pack(method, args...)
	if err != nil {
		e.logger.Error("failed to pack calldata", "method", method, "error", err)
		return nil, fmt.Errorf("pack %s: %w", method, err)
	}

	op, err := e.newOperationWithTransactions(transactTypes.Transaction{
		To:    target,
		Value: big.NewInt(0),
		Data:  calldata,
	})
	if err != nil {
		e.logger.Error("failed to construct operation", "method", method, "error", err)
		return nil, fmt.Errorf("new operation: %w", err)
	}

	return op, nil
}

func generateOperationID() (*big.Int, error) {
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		return nil, err
	}
	return new(big.Int).SetBytes(b), nil
}
