// Code generated by crec-gen. DO NOT EDIT.

package operations

import (
	"math/big"

	"github.com/ethereum/go-ethereum/common"

	transactTypes "github.com/smartcontractkit/crec-sdk/transact/types"
)

var (
	_ = big.NewInt
	_ = common.Address{}
	_ *transactTypes.Operation
)

// PrepareAcceptSettlementOperation prepares a acceptSettlement operation on CCIPDVPCoordinator.
func (e *Extension) PrepareAcceptSettlementOperation(settlementHash [32]byte) (*transactTypes.Operation, error) {
	return e.prepareCCIPDVPCoordinatorOp("acceptSettlement", settlementHash)
}

// PrepareCancelOperation prepares a cancel operation on CCIPDVPCoordinator.
func (e *Extension) PrepareCancelOperation(settlementHash [32]byte) (*transactTypes.Operation, error) {
	return e.prepareCCIPDVPCoordinatorOp("cancel", settlementHash)
}

// PrepareExecuteSettlementOperation prepares a executeSettlement operation on CCIPDVPCoordinator.
func (e *Extension) PrepareExecuteSettlementOperation(settlementHash [32]byte) (*transactTypes.Operation, error) {
	return e.prepareCCIPDVPCoordinatorOp("executeSettlement", settlementHash)
}

// PrepareExecuteSettlementWithTokenDataOperation prepares a executeSettlementWithTokenData operation on CCIPDVPCoordinator.
func (e *Extension) PrepareExecuteSettlementWithTokenDataOperation(settlementHash [32]byte, tokenData []byte) (*transactTypes.Operation, error) {
	return e.prepareCCIPDVPCoordinatorOp("executeSettlementWithTokenData", settlementHash, tokenData)
}

// PrepareRenounceOwnershipOperation prepares a renounceOwnership operation on CCIPDVPCoordinator.
func (e *Extension) PrepareRenounceOwnershipOperation() (*transactTypes.Operation, error) {
	return e.prepareCCIPDVPCoordinatorOp("renounceOwnership")
}

// PrepareSetDVPCoordinatorOperation prepares a setDVPCoordinator operation on CCIPDVPCoordinator.
func (e *Extension) PrepareSetDVPCoordinatorOperation(chainSelector uint64, coordinator common.Address) (*transactTypes.Operation, error) {
	return e.prepareCCIPDVPCoordinatorOp("setDVPCoordinator", chainSelector, coordinator)
}

// PrepareTransferOwnershipOperation prepares a transferOwnership operation on CCIPDVPCoordinator.
func (e *Extension) PrepareTransferOwnershipOperation(newOwner common.Address) (*transactTypes.Operation, error) {
	return e.prepareCCIPDVPCoordinatorOp("transferOwnership", newOwner)
}
