// Code generated by crec-gen. DO NOT EDIT.

package operations

import (
	"crypto/rand"
	"fmt"
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/common"

	transactTypes "github.com/smartcontractkit/crec-sdk/transact/types"
)

var (
	_ = rand.Read
	_ = fmt.Sprintf
	_ = big.NewInt
	_ *abi.ABI
	_ = common.Address{}
	_ *transactTypes.Operation
)

// PrepareCCIPDVPCoordinatorUOperation prepares a generic operation on CCIPDVPCoordinatorU.
// Use this for methods not covered by the type-safe Prepare* functions.
func (e *Extension) PrepareCCIPDVPCoordinatorUOperation(method string, args ...interface{}) (*transactTypes.Operation, error) {
	return e.prepareOperation(CCIPDVPCoordinatorUABI(), e.ccipdvpCoordinatorUAddress, method, args...)
}

func (e *Extension) prepareCCIPDVPCoordinatorUOp(method string, args ...interface{}) (*transactTypes.Operation, error) {
	return e.prepareOperation(CCIPDVPCoordinatorUABI(), e.ccipdvpCoordinatorUAddress, method, args...)
}

func (e *Extension) prepareOperation(
	contractABI *abi.ABI,
	target common.Address,
	method string,
	args ...interface{},
) (*transactTypes.Operation, error) {
	calldata, err := contractABI.Pack(method, args...)
	if err != nil {
		e.logger.Error("failed to pack calldata", "method", method, "error", err)
		return nil, fmt.Errorf("pack %s: %w", method, err)
	}

	opID, err := generateOperationID()
	if err != nil {
		e.logger.Error("failed to generate operation ID", "error", err)
		return nil, fmt.Errorf("generate operation ID: %w", err)
	}

	return &transactTypes.Operation{
		ID:      opID,
		Account: e.accountAddress,
		Transactions: []transactTypes.Transaction{
			{
				To:    target,
				Value: big.NewInt(0),
				Data:  calldata,
			},
		},
	}, nil
}

func generateOperationID() (*big.Int, error) {
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		return nil, err
	}
	return new(big.Int).SetBytes(b), nil
}
