// Code generated by crec-gen. DO NOT EDIT.

package operations

import (
	"math/big"

	"github.com/ethereum/go-ethereum/common"

	transactTypes "github.com/smartcontractkit/crec-sdk/transact/types"
)

var (
	_ = big.NewInt
	_ = common.Address{}
	_ *transactTypes.Operation
)

// PrepareAcceptSettlementOperation prepares a acceptSettlement operation on CCIPDVPCoordinatorU.
func (e *Extension) PrepareAcceptSettlementOperation(settlementHash [32]byte) (*transactTypes.Operation, error) {
	return e.prepareCCIPDVPCoordinatorUOp("acceptSettlement", settlementHash)
}

// PrepareCancelOperation prepares a cancel operation on CCIPDVPCoordinatorU.
func (e *Extension) PrepareCancelOperation(settlementHash [32]byte) (*transactTypes.Operation, error) {
	return e.prepareCCIPDVPCoordinatorUOp("cancel", settlementHash)
}

// PrepareExecuteSettlementOperation prepares a executeSettlement operation on CCIPDVPCoordinatorU.
func (e *Extension) PrepareExecuteSettlementOperation(settlementHash [32]byte) (*transactTypes.Operation, error) {
	return e.prepareCCIPDVPCoordinatorUOp("executeSettlement", settlementHash)
}

// PrepareExecuteSettlementWithTokenDataOperation prepares a executeSettlementWithTokenData operation on CCIPDVPCoordinatorU.
func (e *Extension) PrepareExecuteSettlementWithTokenDataOperation(settlementHash [32]byte, tokenData []byte) (*transactTypes.Operation, error) {
	return e.prepareCCIPDVPCoordinatorUOp("executeSettlementWithTokenData", settlementHash, tokenData)
}

// PrepareRenounceOwnershipOperation prepares a renounceOwnership operation on CCIPDVPCoordinatorU.
func (e *Extension) PrepareRenounceOwnershipOperation() (*transactTypes.Operation, error) {
	return e.prepareCCIPDVPCoordinatorUOp("renounceOwnership")
}

// PrepareSetDVPCoordinatorOperation prepares a setDVPCoordinator operation on CCIPDVPCoordinatorU.
func (e *Extension) PrepareSetDVPCoordinatorOperation(chainSelector uint64, coordinator common.Address) (*transactTypes.Operation, error) {
	return e.prepareCCIPDVPCoordinatorUOp("setDVPCoordinator", chainSelector, coordinator)
}

// PrepareTransferOwnershipOperation prepares a transferOwnership operation on CCIPDVPCoordinatorU.
func (e *Extension) PrepareTransferOwnershipOperation(newOwner common.Address) (*transactTypes.Operation, error) {
	return e.prepareCCIPDVPCoordinatorUOp("transferOwnership", newOwner)
}
