// Code generated by crec-gen. DO NOT EDIT.

package events

import (
	"fmt"
	"strconv"

	"github.com/ethereum/go-ethereum/common"
	"github.com/smartcontractkit/crec-sdk/parsing"
)

var (
	_ = fmt.Sprintf
	_ = strconv.ParseBool
	_ = common.Address{}
	_ = parsing.ScientificNotationToBigInt
)

// ConcreteEvent represents any decoded concrete event payload.
type ConcreteEvent interface{}

// EventDecoder is a function that decodes event parameters into a concrete event type.
type EventDecoder func(params map[string]string, txHash string) (ConcreteEvent, error)

// eventDecoders maps event names to their decoder functions.
var eventDecoders = map[EventName]EventDecoder{
	EventCCIPFeeDeficit:                   decodeCCIPFeeDeficit,
	EventDVPCoordinatorRegistered:         decodeDVPCoordinatorRegistered,
	EventOwnershipTransferred:             decodeOwnershipTransferred,
	EventSettlementAccepted:               decodeSettlementAccepted,
	EventSettlementCanceled:               decodeSettlementCanceled,
	EventSettlementCanceling:              decodeSettlementCanceling,
	EventSettlementClosing:                decodeSettlementClosing,
	EventSettlementMessageProcessingError: decodeSettlementMessageProcessingError,
	EventSettlementOpened:                 decodeSettlementOpened,
	EventSettlementSettled:                decodeSettlementSettled,
}

// EventDecoders returns the map of event decoders.
func EventDecoders() map[EventName]EventDecoder {
	return eventDecoders
}

func decodeCCIPFeeDeficit(params map[string]string, _ string) (ConcreteEvent, error) {
	settlementId, err := parsing.ScientificNotationToBigInt(params["settlement_id"])
	if err != nil {
		return nil, fmt.Errorf("parse settlement_id %q: %w", params["settlement_id"], err)
	}
	currentBalance, err := parsing.ScientificNotationToBigInt(params["current_balance"])
	if err != nil {
		return nil, fmt.Errorf("parse current_balance %q: %w", params["current_balance"], err)
	}
	calculatedFees, err := parsing.ScientificNotationToBigInt(params["calculated_fees"])
	if err != nil {
		return nil, fmt.Errorf("parse calculated_fees %q: %w", params["calculated_fees"], err)
	}
	return &CCIPFeeDeficit{
		SettlementId:   settlementId,
		CurrentBalance: currentBalance,
		CalculatedFees: calculatedFees,
	}, nil
}

func decodeDVPCoordinatorRegistered(params map[string]string, _ string) (ConcreteEvent, error) {
	chainSelector, err := parsing.ScientificNotationToUint64(params["chain_selector"])
	if err != nil {
		return nil, fmt.Errorf("parse chain_selector %q: %w", params["chain_selector"], err)
	}
	return &DVPCoordinatorRegistered{
		ChainSelector: chainSelector,
		Coordinator:   common.HexToAddress(params["coordinator"]),
	}, nil
}

func decodeOwnershipTransferred(params map[string]string, _ string) (ConcreteEvent, error) {
	return &OwnershipTransferred{
		PreviousOwner: common.HexToAddress(params["previous_owner"]),
		NewOwner:      common.HexToAddress(params["new_owner"]),
	}, nil
}

func decodeSettlementAccepted(params map[string]string, _ string) (ConcreteEvent, error) {
	settlementId, err := parsing.ScientificNotationToBigInt(params["settlement_id"])
	if err != nil {
		return nil, fmt.Errorf("parse settlement_id %q: %w", params["settlement_id"], err)
	}
	return &SettlementAccepted{
		SettlementId:   settlementId,
		SettlementHash: common.HexToHash(params["settlement_hash"]),
	}, nil
}

func decodeSettlementCanceled(params map[string]string, _ string) (ConcreteEvent, error) {
	settlementId, err := parsing.ScientificNotationToBigInt(params["settlement_id"])
	if err != nil {
		return nil, fmt.Errorf("parse settlement_id %q: %w", params["settlement_id"], err)
	}
	return &SettlementCanceled{
		SettlementId:   settlementId,
		SettlementHash: common.HexToHash(params["settlement_hash"]),
	}, nil
}

func decodeSettlementCanceling(params map[string]string, _ string) (ConcreteEvent, error) {
	settlementId, err := parsing.ScientificNotationToBigInt(params["settlement_id"])
	if err != nil {
		return nil, fmt.Errorf("parse settlement_id %q: %w", params["settlement_id"], err)
	}
	return &SettlementCanceling{
		SettlementId:   settlementId,
		SettlementHash: common.HexToHash(params["settlement_hash"]),
	}, nil
}

func decodeSettlementClosing(params map[string]string, _ string) (ConcreteEvent, error) {
	settlementId, err := parsing.ScientificNotationToBigInt(params["settlement_id"])
	if err != nil {
		return nil, fmt.Errorf("parse settlement_id %q: %w", params["settlement_id"], err)
	}
	return &SettlementClosing{
		SettlementId:   settlementId,
		SettlementHash: common.HexToHash(params["settlement_hash"]),
	}, nil
}

func decodeSettlementMessageProcessingError(params map[string]string, _ string) (ConcreteEvent, error) {
	return &SettlementMessageProcessingError{
		MessageId: common.HexToHash(params["message_id"]),
		ErrorData: []byte(params["error_data"]),
	}, nil
}

func decodeSettlementOpened(params map[string]string, _ string) (ConcreteEvent, error) {
	settlementId, err := parsing.ScientificNotationToBigInt(params["settlement_id"])
	if err != nil {
		return nil, fmt.Errorf("parse settlement_id %q: %w", params["settlement_id"], err)
	}
	return &SettlementOpened{
		SettlementId:   settlementId,
		SettlementHash: common.HexToHash(params["settlement_hash"]),
	}, nil
}

func decodeSettlementSettled(params map[string]string, _ string) (ConcreteEvent, error) {
	settlementId, err := parsing.ScientificNotationToBigInt(params["settlement_id"])
	if err != nil {
		return nil, fmt.Errorf("parse settlement_id %q: %w", params["settlement_id"], err)
	}
	return &SettlementSettled{
		SettlementId:   settlementId,
		SettlementHash: common.HexToHash(params["settlement_hash"]),
	}, nil
}
