// Code generated by crec-gen. DO NOT EDIT.

package events

import (
	"math/big"

	"github.com/ethereum/go-ethereum/common"
)

var (
	_ = big.NewInt
	_ = common.Address{}
	_ = common.Hash{}
)

// EventName represents an event name from the contracts.
type EventName string

const (
	EventCCIPFeeDeficit                   EventName = "CCIPFeeDeficit"
	EventDVPCoordinatorRegistered         EventName = "DVPCoordinatorRegistered"
	EventOwnershipTransferred             EventName = "OwnershipTransferred"
	EventSettlementAccepted               EventName = "SettlementAccepted"
	EventSettlementCanceled               EventName = "SettlementCanceled"
	EventSettlementCanceling              EventName = "SettlementCanceling"
	EventSettlementClosing                EventName = "SettlementClosing"
	EventSettlementMessageProcessingError EventName = "SettlementMessageProcessingError"
	EventSettlementOpened                 EventName = "SettlementOpened"
	EventSettlementSettled                EventName = "SettlementSettled"
	EventUnknown                          EventName = "Unknown"
)

var allEvents = map[string]EventName{
	string(EventCCIPFeeDeficit):                   EventCCIPFeeDeficit,
	string(EventDVPCoordinatorRegistered):         EventDVPCoordinatorRegistered,
	string(EventOwnershipTransferred):             EventOwnershipTransferred,
	string(EventSettlementAccepted):               EventSettlementAccepted,
	string(EventSettlementCanceled):               EventSettlementCanceled,
	string(EventSettlementCanceling):              EventSettlementCanceling,
	string(EventSettlementClosing):                EventSettlementClosing,
	string(EventSettlementMessageProcessingError): EventSettlementMessageProcessingError,
	string(EventSettlementOpened):                 EventSettlementOpened,
	string(EventSettlementSettled):                EventSettlementSettled,
}

// ParseEventName converts a string to an EventName if recognized.
func ParseEventName(value string) (EventName, bool) {
	ev, ok := allEvents[value]
	return ev, ok
}

func (ev EventName) String() string {
	return string(ev)
}

// CCIPFeeDeficit event.
type CCIPFeeDeficit struct {
	SettlementId   *big.Int `json:"settlement_id"`
	CurrentBalance *big.Int `json:"current_balance"`
	CalculatedFees *big.Int `json:"calculated_fees"`
}

// DVPCoordinatorRegistered event.
type DVPCoordinatorRegistered struct {
	ChainSelector uint64         `json:"chain_selector"`
	Coordinator   common.Address `json:"coordinator"`
}

// OwnershipTransferred event.
type OwnershipTransferred struct {
	PreviousOwner common.Address `json:"previous_owner"`
	NewOwner      common.Address `json:"new_owner"`
}

// SettlementAccepted event.
type SettlementAccepted struct {
	SettlementId   *big.Int    `json:"settlement_id"`
	SettlementHash common.Hash `json:"settlement_hash"`
}

// SettlementCanceled event.
type SettlementCanceled struct {
	SettlementId   *big.Int    `json:"settlement_id"`
	SettlementHash common.Hash `json:"settlement_hash"`
}

// SettlementCanceling event.
type SettlementCanceling struct {
	SettlementId   *big.Int    `json:"settlement_id"`
	SettlementHash common.Hash `json:"settlement_hash"`
}

// SettlementClosing event.
type SettlementClosing struct {
	SettlementId   *big.Int    `json:"settlement_id"`
	SettlementHash common.Hash `json:"settlement_hash"`
}

// SettlementMessageProcessingError event.
type SettlementMessageProcessingError struct {
	MessageId common.Hash `json:"message_id"`
	ErrorData []byte      `json:"error_data"`
}

// SettlementOpened event.
type SettlementOpened struct {
	SettlementId   *big.Int    `json:"settlement_id"`
	SettlementHash common.Hash `json:"settlement_hash"`
}

// SettlementSettled event.
type SettlementSettled struct {
	SettlementId   *big.Int    `json:"settlement_id"`
	SettlementHash common.Hash `json:"settlement_hash"`
}
